services:
  - type: web
    name: relevance-ai-dashboard-api
    runtime: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    pythonVersion: 3.9.18
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
      - key: PYTHONPATH
        value: .